### ISSUE TITLE
Updating a DID fails when the anchor origin is down

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/orb#1136]
Steps to reproduce:
- Domain1, Domain2 and Domain3 are all following and witnessing each other
- Create a DID on Domain3 (Domain1 and Domain2 witness the anchor)
- Shut down Domain3
- Update the created DID on Domain1

Results in the following error:

`orb.domain1.com              |  [sidetree-core-writer] 2022/02/18 20:54:55 UTC - batch.(*Writer).cutAndProcess -> ERROR [did:orb] Error processing 17 batch operations: failed to create witness list: resolve witness: failed to resolve witness: failed to get key[https://orb.domain3.com] from host metadata cache: failed to get host-meta document via HTTP/HTTPS: failed to get a response from the host-meta endpoint: Get "https://orb.domain3.com/.well-known/host-meta.json": dial tcp: lookup orb.domain5.com on 127.0.0.11:53: no such host
`

And the batch is never anchored.

The expectation is that, since Domain2 is still up then Domain2 can witness the update and the batch should be anchored.

**Comment by fqutishat** [comment]
VDR change to use different domain when anchor origin is down

**Comment by fqutishat** [comment]
https://github.com/hyperledger/aries-framework-go-ext/pull/280
