### ISSUE TITLE
Comments on TrustBloc Key document

### ISSUE THREAD

**Issue by rmm-sk** [trustbloc/orb#1160]
Ref: https://trustbloc.readthedocs.io/en/latest/orb/key.html

**Comment 1:** If #1159 is accepted and actioned, ensure document is updated to outline the use of 2 single purpose orb keys rather than 1 key for multiple purposes. In the meantime, suggest make sentence 2 and 3 of first section ("Key") into bullets.

**Comment 2:**
Suggest add note in Section "Key" that Orb uses an ed25519 key. Also, I know this is needed for VC signing to provide data minimization, but if the http requests are given their own key, does it still make the most sense to use ed25519? Are there are keys that are better suited for signing http requests?

**Comment 3:**
Section: "Creation "- indicates there are 2 ways to create orb key, but it is not clear from the section headings what those two ways are. Do you mean: 
 (1) Import a pre-existing private key into KMS at Orb startup via Orb configuration 
 (2) Create a new key within KMS, and establish Orb configuration with this key (before starting Orb) 
?

If yes: suggest change: 
> Creation
>There are 2 ways to establish the orb key:
> - Import a pre-existing private key and id into KMS at Orb startup via Orb configuration
> - Prior to orb startup, create a new key within KMS and establish orb configuration 

Also suggest change section names to align with import versus create concept:
>Change "Creation" to "Establish orb key"
>Change "Private key" to "Add pre-existing private key to orb configuration"
>Change "KMS key id" to "Create private key in KMS and configure orb to use"

**Comment 4:**
Section "Private key/Steps to create key" - Where is the ed25519 key created? What crypto library would be used to create it? Or is this deemed outside the scope of Orb.

**Comment by rmm-sk** [comment]
**Comment 5:**
Section: "Impact of loss" - loss of private key does not impact signature validation (as that is done with the public key). So I think it should be just that new VCs cannot be signed if the key is lost (corrupted/overwritten/etc). So there is an availability risk. If compromised, another entity could sign VCs on behalf of orb. Actually - is orb actually signing VCs? Wouldn't Issuers do that?

**Comment by troyronda** [comment]
@rmm-sk The proofs from orb witnesses are in VC format. So in the context of Orb, signing a VC means the Orb anchor event VC. Orb service doesn’t sign other VCs - that’s for the relevant VC issuers.

**Comment by troyronda** [comment]
@rmm-sk The proofs from orb witnesses are in VC format. So in the context of Orb, signing a VC means the Orb anchor event VC. Orb service doesn’t sign other VCs - that’s for the relevant VC issuers.
