### ISSUE TITLE
ALLOWED_ORIGINS

### ISSUE THREAD

**Issue by alialkhalidi** [trustbloc/orb#1362]
Currently, ALLOWED_ORIGINS is a startup config parameter that controls the allowed origins for the did method. 
In a multi-domain orb network, and when a new orb domain is onboarded to the network, this requires updating and restarting all existing orb domain instances, which affects the availability of the overall network unjustifiably (confirmed with the orb team).

The proposal is to have an endpoint where this can be done for each orb domain at run-time, without requiring a restart of the orb instances.

- [x] #1377 
- [x] #1378 
- [x] #1379

**Comment by bstasyszyn** [comment]
Done
