### ISSUE TITLE
Rename "also known as" sidetree patch

### ISSUE THREAD

**Issue by troyronda** [trustbloc/orb#1410]
Remove the '-' prefix from the patches.

**Comment by sandrask** [comment]
- replace "-add-also-known-as" and "-remove-also-known-as" with "add-also-known-as" and "remove-also-known-as" (no custom patch prefix '-') in three protocol.go files (mock, v1_0, v_test) 
- update sidetree-core-go version and aries-framework-go-ext version(this library has special dependencies between VDRs and Orb - talk to @fqutishat  on how to update)
