### ISSUE TITLE
function abspath missing

### ISSUE THREAD

**Issue by TomCJones** [trustbloc/orb#381]
I found (abspath .) missing in Makefile and was able to patch that to move on. but then i get this - i have other implementations of abspath, but wanted a working repo so i am not sure how to proceed.

time="2021-05-11T12:33:40-07:00" level=warning msg="Error generating logs: Error issuing command to docker-compose with args '[logs]':  exit status 255 ([3752] Failed to execute script docker-compose\nTraceback (most recent call last):\n  File \"docker-compose\", line 3, in <module>\n  File \"compose/cli/main.py\", line 81, in main\n  File \"compose/cli/main.py\", line 199, in perform_command\n  File \"compose/cli/command.py\", line 70, in project_from_options\n  File \"compose/cli/command.py\", line 146, in get_project\n  File \"compose/cli/command.py\", line 206, in get_project_name\n  File \"posixpath.py\", line 383, in abspath\nFileNotFoundError: [Errno 2] No such file or directory\n)"
2021/05/11 12:33:41 Error issuing command to docker-compose with args '[stop]':  exit status 255 ([3754] Failed to execute script docker-compose
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 199, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 146, in get_project
  File "compose/cli/command.py", line 206, in get_project_name
  File "posixpath.py", line 383, in abspath
FileNotFoundError: [Errno 2] No such file or directory
)

**Comment by troyronda** [comment]
@TomCJones I'd like to reproduce this issue.

I tried a fresh ubuntu-20.04 server instance and installed:
- make
- gcc
- go 1.16.4
- docker
- docker-compose

I successfully ran in bash shell:
`make bdd-test` in the `orb` directory.
 
What's your environment and shell?
What command did you try running?

**Comment by troyronda** [comment]
in bash of fresh ubuntu-20.04:

sudo apt update
sudo apt-get install make gcc
sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt install docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker $USER

<exit and relogin>

sudo apt install docker-compose

wget https://golang.org/dl/go1.16.4.linux-amd64.tar.gz
tar -xzf go1.16.4.linux-amd64.tar.gz
sudo mv go /usr/local
export PATH=$PATH:/usr/local/go/bin

git clone https://github.com/trustbloc/orb.git
cd orb
make bdd-test

**Comment by TomCJones** [comment]
Thanks for that - I have always been careful about the supply chain, but since Solar Winds have been paranoid about it. I will try to get a minimum list of dependencies together and post it.
