### ISSUE TITLE
Add policy parser/evaluator

### ISSUE THREAD

**Issue by sandrask** [trustbloc/orb#445]
Default behaviour: 100% system and 100% batch

Examples for minimum percent of witnesses required:
MinPercent(50,system) AND MinPercent(100,batch)
MinPercent(50,system) OR MinPercent(50,batch)
MinPercent(20,system) AND MinPercent(0,batch)

Examples for minimum number:
OutOf(1,system) - minimum 1 system witnesss
OutOf(1,batch) - minimum 1 batch witnesss

This will probably be less used than minimum percent rule, can be used with OR and AND as well.

**Comment by troyronda** [comment]
Also we need to split the attempts (aka offers) from the requirement to receive responses.
