### ISSUE TITLE
Use web-finger to resolve ActivityPub actors

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/orb#482]
For example: https://alice.example.com/.well-known/webfinger?resource=https%3A%2F%2Falice.example.com%2Fservices%2Forb returns:

```
{
  “subject”: “https://alice.example.com/services/orb”,
  “links”: [
    {
      “rel”: “self”,
      “type”: “application/activity+json”,
      “href”: “https://alice.example.com/services/orb”
    },
    {
      “rel”: “alternate”,
      “type”: “application/activity+json”,
      “href”: “https://alice2.example.com/services/orb”
    }
  ]
}
```

**Comment by bstasyszyn** [comment]
This is not required since the actor is already returned via a WebFinger query, or /witnesses, /followers query.

**Comment by troyronda** [comment]
To obtain an activitypub actor's endpoints, you need to first use WebFinger on the actor URI. @bstasyszyn
