### ISSUE TITLE
Update anchor data model

### ISSUE THREAD

**Issue by troyronda** [trustbloc/orb#581]
Sample:

```
{
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        "https://w3id.org/activityanchors/v1"
    ],
    "type": "AnchorEvent",
    "attributedTo": "ipns://k51qzi5uqu5dl3ua2aal8vdw82j4i8s112p495j1spfkd2blqygghwccsw1z0p",
    "published": "2021-01-27T09:30:00Z",
    "previous": [{
        "id": "urn:multihash:u2ouBBsyLDedeYciUmaihjWUmWhA3LVkruPZwSk7EeHWWqUZF",
        "url": "ipfs://bafkreicdkwsgwgotjdoc6v6ai34o6y6ukohlxe3aadz4t3uvjitumdoymu",
        "type": "Link"
    }],
    "attachment": [{
        "type": "AnchorIndex",
        "generator": "https://w3id.org/orb#v1",
        "url": [
            {
                "href": "ipfs://bafkreihwsnuregceqh263vgdathcprnbvatyat6h6mu7ipjhhodcdbyhoy",
                "type": "Link",
                "rel": "self"
            },
            {
                "href": "https://example.com/cas/bafkreihwsnuregceqh263vgdathcprnbvatyat6h6mu7ipjhhodcdbyhoy",
                "type": "Link",
                "rel": "alternate"
            }
        ],
        "resources": [
            "urn:multihash:uEiDahaOGH-liLLdDtTxEAdc8i-cfCz-WUcQdRJheMVNn3A",
            {
                "id": "urn:multihash:uEiA329wd6Aj36YRmp7NGkeB5ADnVt8ARdMZMPzfXsjwTJA",
                "previousAnchor": "urn:multihash:u2ouBBsyLDedeYciUmaihjWUmWhA3LVkruPZwSk7EeHWWqUZF",
                "type": "AnchorResource"
            }
        ]
    }]
}
```

**Comment by sandrask** [comment]
`                "credentialSubject": {
                  "type": "AnchorEvent",
                  "previous": [
                    {
                      "id": "urn:multihash:u2ouBBsyLDedeYciUmaihjWUmWhA3LVkruPZwSk7EeHWWqUZF",
                      "url": "ipfs://bafkreicdkwsgwgotjdoc6v6ai34o6y6ukohlxe3aadz4t3uvjitumdoymu",
                      "type": "Link"
                    },
                    {
                      "id": "urn:multihash:uEiBTwjTl6EcrasUcGuHKs_4G-tBTvrjr_Yl3sBBlW_3Twwo",
                      "url": "ipfs://bafkreictyi2ol2chfnvmkha24hflh7qg7lifhpvy5p6ys55qcbsvx7otym",
                      "type": "Link"
                    }
                  ],
                  "attachment": [{
                    "type": "AnchorIndex",
                    "generator": "https://example.com/spec#v1",
                    "url": [
                      {
                          "href": "ipfs://bafkreihwsnuregceqh263vgdathcprnbvatyat6h6mu7ipjhhodcdbyhoy",
                          "type": "Link",
                          "rel": "self"
                      },
                      {
                          "href": "https://example.com/cas/bafkreihwsnuregceqh263vgdathcprnbvatyat6h6mu7ipjhhodcdbyhoy",
                          "type": "Link",
                          "rel": "alternate"
                      }
                    ],
                    "resources": [
                        "urn:multihash:uEiDahaOGH-liLLdDtTxEAdc8i-cfCz-WUcQdRJheMVNn3A",
                        {
                            "id": "urn:multihash:uEiA329wd6Aj36YRmp7NGkeB5ADnVt8ARdMZMPzfXsjwTJA",
                            "previousAnchor": "urn:multihash:u2ouBBsyLDedeYciUmaihjWUmWhA3LVkruPZwSk7EeHWWqUZF",
                            "type": "AnchorResource"
                        },
                        {
                          "id": "urn:multihash:uEiARIc_M1ZE_CmP-xApv_UTqZPncE1xmY0ugAdELz0MCogo",
                          "previousAnchor": "urn:multihash:uEiBTwjTl6EcrasUcGuHKs_4G-tBTvrjr_Yl3sBBlW_3Twwo",
                          "type": "AnchorResource"
                      }
                    ]
                  }

**Comment by sandrask** [comment]
Another example: 
```
{
   "type":"AnchorEvent",
   "attributedTo":"ipns://k51qzi5uqu5dl3ua2aal8vdw82j4i8s112p495j1spfkd2blqygghwccsw1z0p",
   "published":"2021-01-27T09:30:00Z",
   "previous":[
      {
         "id":"urn:multihash:u2ouBBsyLDedeYciUmaihjWUmWhA3LVkruPZwSk7EeHWWqUZF",
         "url":"ipfs://bafkreicdkwsgwgotjdoc6v6ai34o6y6ukohlxe3aadz4t3uvjitumdoymu",
         "type":"Link"
      },
      {
         "id":"urn:multihash:uEiBTwjTl6EcrasUcGuHKs_4G-tBTvrjr_Yl3sBBlW_3Twwo",
         "url":"ipfs://bafkreictyi2ol2chfnvmkha24hflh7qg7lifhpvy5p6ys55qcbsvx7otym",
         "type":"Link"
      }
   ],
   "attachment":[
      {
         "type":"AnchorIndex",
         "generator":"https://example.com/spec#v1",
         "url":[
            {
               "href":"ipfs://bafkreihwsnuregceqh263vgdathcprnbvatyat6h6mu7ipjhhodcdbyhoy",
               "type":"Link",
               "rel":"self"
            },
            {
               "href":"https://example.com/cas/bafkreihwsnuregceqh263vgdathcprnbvatyat6h6mu7ipjhhodcdbyhoy",
               "type":"Link",
               "rel":"alternate"
            }
         ],
         "resources":[
            "urn:multihash:uEiDahaOGH-liLLdDtTxEAdc8i-cfCz-WUcQdRJheMVNn3A",
            {
               "id":"urn:multihash:uEiA329wd6Aj36YRmp7NGkeB5ADnVt8ARdMZMPzfXsjwTJA",
               "previousAnchor":"urn:multihash:u2ouBBsyLDedeYciUmaihjWUmWhA3LVkruPZwSk7EeHWWqUZF",
               "type":"AnchorResource"
            },
            {
               "id":"urn:multihash:uEiARIc_M1ZE_CmP-xApv_UTqZPncE1xmY0ugAdELz0MCogo",
               "previousAnchor":"urn:multihash:uEiBTwjTl6EcrasUcGuHKs_4G-tBTvrjr_Yl3sBBlW_3Twwo",
               "type":"AnchorResource"
            }
         ]
      }
   ]
}
```

**Comment by troyronda** [comment]
@sandrask Fixed.
